### ISSUE TITLE
Change material order in Warehouse

### ISSUE THREAD

**Issue by Zari0t** [windbow27/kornblume#103]
The new leveling materials/drops in the warehouse were added to the end of their respective tiers, but in-game they're in a different order. I'm pretty sure the exact same thing happened with the 1.4 update.
https://zari0t.s-ul.eu/3cV2Eryn.png gold
https://zari0t.s-ul.eu/u5rnoYSG.jpg purple/blue
Can't verify orange mat currently

**Comment by windbow27** [comment]
updated, including orange mat
