### ISSUE TITLE
Tooth Fairy's Frequency image error

### ISSUE THREAD

**Issue by cherryburimi** [windbow27/kornblume#104]
1. Run Planner - Add Arcanist - Tooth Fairy
2. CURRENT LEVEL - Insight III
3. Click Frequency

![K-001](https://github.com/user-attachments/assets/4d4b3f95-de08-4e0c-bdb6-abf30f12b60c)

She has a ‘+’ resonance, not a ‘U’ resonance
She is the only 6 star character with different resonance enhancement materials and actual resonance
![K-002](https://github.com/user-attachments/assets/20595764-bf7e-48b6-8801-60730515a557)

**Comment by windbow27** [comment]
the issue has been fixed
