### ISSUE TITLE
Anjo Nala showing on tracker instead of An-an Lee

### ISSUE THREAD

**Issue by ChiiBee** [windbow27/kornblume#105]
Hi, I was uploading my recent Promise of the Water pulls from the Global server and noticed that the tracker said I got Anjo Nala instead of An-an Lee, which is definitely an error considering she's not even out yet lol

![reverse1999_gBls6tOGUR](https://github.com/user-attachments/assets/040e2052-16e9-4281-86f3-4ebd97026a7c)
![image](https://github.com/user-attachments/assets/2550cc95-d30d-4a29-b4c1-cf73e2e499e4)

**Comment by windbow27** [comment]
the issue has been fixed.
