### ISSUE TITLE
T-piece Resonance Frequency picture missing

### ISSUE THREAD

**Issue by Zari0t** [windbow27/kornblume#109]
https://zari0t.s-ul.eu/dWYiSJWL.png as an example, but it looks like this for every arcanist that has a T-piece.
This has actually been like this ever since this feature got added to the tracker, I just never posted about it because I hadn't needed it before.

**Comment by windbow27** [comment]
The actual bug was fixed on that Tooth Fairy patch. This one is another mistake on my part at naming things lol. Fixed.
