### ISSUE TITLE
Resonance Frequency not leveling properly (?)

### ISSUE THREAD

**Issue by Zari0t** [windbow27/kornblume#110]
Currently in the Planner, if you go to any arcanist and click through to their Resonance Frequencies, you can toggle them to add their materials to the farm list. This is, however, the only thing you can do - there is no way to toggle whether or not a Frequency has already been obtained or not (mark it as already obtained). Because of this, pressing _Level Up_ when you have an arcanist's Resonance Frequency toggled on in their plan will spend the materials required to obtain it, but it won't untoggle the Frequency/mark it as obtained in any way AND still keeps the materials in the farm pool, meaning that you will farm for it again if you don't remove it manually or hide/delete the arcanist from your plans.

Having two states for Frequencies, _Farming_ and _Obtained_, would make handling both of these issues easier, whilst also being easier on the end-user for farm planning.

**Comment by windbow27** [comment]
Introducing states might lead to complicated ui (having the border as selected, then potentially another checkbox for the states). I might consider it later, but for now, uncheck the border should suffice.
