### ISSUE TITLE
Crystal casket isn't calculating properly

### ISSUE THREAD

**Issue by oliverysfx** [windbow27/Kornblume#4]
![image](https://github.com/windbow27/Kornblume/assets/54044780/4224a311-e113-4b6b-a3d1-78c5daec3a44)
![image](https://github.com/windbow27/Kornblume/assets/54044780/1aefab7a-c5dd-4432-8da1-0125b15bba1d)
When I set crystal casket amount in my warehouse to 0, the crystal casket and oneiric fluid amount required is properly calculated to 9000
![image](https://github.com/windbow27/Kornblume/assets/54044780/f0963227-b274-4cac-bd43-99ed847c16e9)
![image](https://github.com/windbow27/Kornblume/assets/54044780/119e3191-6888-4294-a444-afe50b2abe71)
However, when I set it to 1, both the number of crystal caskets and oneiric fluid required is calculated incorrectly

**Comment by windbow27** [comment]
Hello there,
Thank you for reporting, the issue has been fixed. We're still working on some stuffs so the deploy will be pushed back a little. 
Cheers!
PS: The next update changes a lot of things, so expect your data be corrupted in some ways or another, sorry for the inconvenience but hope you understand.
