### ISSUE TITLE
[Issue] Purple item order on site is in a different order than in game

### ISSUE THREAD

**Issue by joshboston723** [windbow27/Kornblume#68]
![image](https://github.com/windbow27/Kornblume/assets/83313770/cc6db55d-4de0-49a0-a54b-4eaea90bbbe4)
![image](https://github.com/windbow27/Kornblume/assets/83313770/e3c70590-8ad1-4e0d-8fdd-d6deec33366b)

Did I clear cookies already? Yes.

**Comment by joshboston723** [comment]
Oh snap I didn't notice the website has a google form for comments and suggestions, I'll use that next time

**Comment by windbow27** [comment]
Fixed. And no worries, you can use whatever comfortable. I check them both ;)
