### ISSUE TITLE
Google Drive Sync cannot be logged in on some browsers

### ISSUE THREAD

**Issue by ryle798** [windbow27/kornblume#73]
When I use the Chrome browser on my mobile phone, the website can be logged in and synchronized normally. 
But when I use the kiwi browser, the login button cannot be clicked. 
When I use the Xiaomi browser, I can click the login account button and select the Google account. But it will always display "Please wait" and cannot synchronize normally.

![微信图片_20240309102413](https://github.com/windbow27/Kornblume/assets/161399647/f5858c2b-8334-4e2b-8fdd-ad481e59302c)
![微信图片_20240309102406](https://github.com/windbow27/Kornblume/assets/161399647/a13a9e97-a3c5-4c35-841f-e5aafe7061b0)

**Comment by windbow27** [comment]
i'm not familiar with these browsers, do you know if they work for other sites with google drive?

**Comment by ryle798** [comment]
@windbow27 
On Seelie, the Google Drive login button cannot be clicked on the Kiwi browser.
Xiaomi browser can be logged in and synchronized normally on Seelie.
