### ISSUE TITLE
[BUG]: Recent build changes most of all icons to Bkornblume

### ISSUE THREAD

**Issue by NikarashiHatsu** [windbow27/Kornblume#80]
I already tried to clear the cache, even accessing the site using Incognito. The issue still persists.

![Screenshot 2024-04-01 at 10 12 07](https://github.com/windbow27/Kornblume/assets/43662951/555da17c-1b0f-49da-96b0-043ff223394c)

**Comment by NikarashiHatsu** [comment]
Even the material warehouse facing the same issue.

![Screenshot 2024-04-01 at 10 14 26](https://github.com/windbow27/Kornblume/assets/43662951/723c5949-a2b7-4c4c-a878-b1f38fb9f5d9)

**Comment by windbow27** [comment]
it's not a bug, it's a feature ;)

**Comment by NikarashiHatsu** [comment]
I do really forgot that today was the date lmao 😆
