### ISSUE TITLE
Feature Request: Prefer Crafting over Obtaining Materials

### ISSUE THREAD

**Issue by NikarashiHatsu** [windbow27/kornblume#93]
I do think there are some players (me included) that prefer crafting over obtaining "rare" / gold materials.

**Comment by frantw** [comment]
I think you meant 5-19H (bullets) or 6-14H (specimens).

However, there might be a slight misunderstanding.
It's not prioritizing farming gold materials first; rather, it's considering all drops.
Gold materials are simply a byproduct of this comprehensive approach in linear planning.
