### ISSUE TITLE
Feature Request add support for "FM Resonance" that has been added in version 2.0

### ISSUE THREAD

**Issue by wireconnectbypassnat** [windbow27/kornblume#94]
the info exists in [huijiwiki](https://res1999.huijiwiki.com/wiki/%E5%8D%A1%E5%8D%A1%E5%B0%BC%E4%BA%9A)

the info exists in huijiwiki
[![image](https://i.postimg.cc/rmkDSZhC/5Ezl1zg.png)](https://postimg.cc/Mc9Zw5Jv)

**Comment by windbow27** [comment]
It has been added!
